# Cloudbuild pipeline for a build with an image
# that passes the vuln policy
steps:
  # Build a 'bad' image
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
      - -c
      - |
        docker build -t gcr.io/$PROJECT_ID/binauthz-test:latest -f ./Dockerfile.bad .
    id: build
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
    - -c
    - |
      docker push gcr.io/$PROJECT_ID/binauthz-test:latest &&
      docker image inspect gcr.io/$PROJECT_ID/binauthz-test:latest --format '{{ .ID }}' > image-digest.txt &&
      cat image-digest.txt
    id: push
  # Wait for vulnerability scanning reaults
  - name: gcr.io/$PROJECT_ID/python-builder
    args:
    - ./wait-for-analysis.py 
    - gcr.io/$PROJECT_ID/binauthz-test@$(/bin/cat image-digest.txt)
    - $PROJECT_ID
    id: vulnpoll
  - name: gcr.io/$PROJECT_ID/kritis-signer
    entrypoint: /bin/bash
    args:
    - -c
    - |
      /kritis/signer \
      -v=10 \
      -alsologtostderr \
      -image=gcr.io/$PROJECT_ID/binauthz-test@$(/bin/cat image-digest.txt) \
      -credentials=kritis-service-account.json \
      -private_key=gpg.priv \
      -public_key=gpg.pub \
      -policy=policy.yaml
    waitFor: vulnpoll
    id: vulnsign
images: ['gcr.io/$PROJECT_ID/binauthz-test:latest']
