apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.postinstall.pod.name }}
  namespace: {{ .Values.serviceNamespace }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-delete-policy": "hook-failed"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  restartPolicy: Never
  containers:
  - name: {{ .Values.postinstall.pod.name }}
    image: {{ .Values.postinstall.pod.image }}
    args:
      - "--webhook-name" 
      - {{ .Values.serviceName }}
      - "--service-name"
      - {{ .Values.serviceName }}
      - "--tls-secret-name"
      - {{ .Values.tlsSecretName }}
      - "--deployment-webhook-name"
      - {{ .Values.serviceNameDeployments }}
    command: {{ .Values.postinstall.pod.command }}
