# Gopkg.toml

required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
]
 
[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.0"
 
[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.0"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
