# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  # These are the required packages used by the go container analysis client libs.
  # Do not remove.
  "cloud.google.com/go/compute/metadata",
  "github.com/googleapis/gax-go",
  "cloud.google.com/go/internal/version",
  "google.golang.org/grpc",
  "golang.org/x/oauth2",
  "google.golang.org/appengine",
  "google.golang.org/api/googleapi",
  "google.golang.org/api/internal",
  "google.golang.org/api/option",
  "google.golang.org/api/transport",
  "google.golang.org/grpc/credentials",
  "google.golang.org/appengine/socket",
  "google.golang.org/appengine/internal",
]

# Add this ignore to ignore dependency resolution error for imports
# "cloud.google.com/go/devtools"
ignored = ["cloud.google.com/go/devtools/*"]

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0-beta.2"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.0-beta.2"

[[constraint]]
  version = "kubernetes-1.10.0"
  name = "k8s.io/apimachinery"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false

[[constraint]]
  name = "gopkg.in/d4l3k/messagediff.v1"
  revision = "b9e99b2f9263a86c71c1ca4507f34502448c58a4"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.4.0"
