steps:
  # Build kritis
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "deploy/Dockerfile",
           "-t", "gcr.io/kritis-project/kritis-server:${COMMIT_SHA}", "."]
images: ["gcr.io/kritis-project/kritis-server:${COMMIT_SHA}"]
