apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.predelete.pod.name }}
  namespace: {{ .Values.serviceNamespace }}
  annotations:
    "helm.sh/hook": "pre-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-delete-policy": "hook-failed"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "kritis.grafeas.io/breakglass": "true"
spec:
  serviceAccountName: {{ .Values.preinstall.serviceAccount }}
  restartPolicy: Never
  containers:
  - name: {{ .Values.predelete.pod.name }}
    image: {{ .Values.predelete.pod.image }}
    args:
    - "--webhook-name"
    - {{ .Values.serviceName }}
    - "--deployment-webhook-name"
    - {{ .Values.serviceNameDeployments }}
    - "--tls-secret-name"
    - {{ .Values.tlsSecretName }}
    - "--csr-name"
    - {{ .Values.csrName }}
    command: {{ .Values.predelete.pod.command }}
