apiVersion: kritis.grafeas.io/v1beta1
kind: GenericAttestationPolicy
metadata:
  name: my-gap
  namespace: default
spec:
  attestationAuthorityNames:
  - kritis-authority
  imageAllowlist:
  - gcr.io/my/image
