apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: imagesecuritypolicies.kritis.grafeas.io
spec:
  group: kritis.grafeas.io
  version: v1beta1
  names:
    kind: ImageSecurityPolicy
    plural: imagesecuritypolicies
  scope: Namespaced
